### ISSUE TITLE
Emails found: 0 NOT WORKING

### ISSUE THREAD

**Issue by adsantoli** [hedii/php-crawler#34]
The Urls Statistics show:  NaN%  
And no emails are found.

Do you know why this is?  please advise  thank you

![screen shot 2018-11-15 at 8 23 21 pm](https://user-images.githubusercontent.com/17833508/48597796-749f1300-e914-11e8-95c2-96140e27a4c1.png)

**Comment by hedii** [comment]
Cannot help without any js log, php log, etc...

**Comment by hedii** [comment]
@adsantoli 
I've just tested on your website (zippy.zone), with the same search (www.yellowpages.com): everything works fine. The NaN% is shown only during the first seconds, and after that we get a real percentage.

Can you give me a couple of url on yellowpages.com that are supposed to contain email addresses?

I think your problem is that there is no email in the html content of this website, but the crawler is doing its job.

<img width="1041" alt="capture d ecran 2018-11-16 a 08 54 14" src="https://user-images.githubusercontent.com/5358048/48605602-87016700-e97d-11e8-9db3-222204096776.png">

**Comment by MHassanSaqib** [comment]
Same issue there. What's happening? Any solution?
